### s3 ###

apiVersion: s3.aws.crossplane.io
kind: Bucket
metadata:
  name: paas-s3-cp-sherifkunch-unique-bucket   ## bucket name must be unique 
spec:
  forProvider:
    acl: private
    locationConstraint: eu-central-1
    objectLockEnabledForBucket: false
  providerConfigRef:
    name: awsconfig